[module]
  [module.hugoVersion]
    extended = true
    min = '0.90.0'

[params]
  show_related = true
  centerTheme = true
  custom_css = ["css/style.css"]
  readingTime = true
  summaryLength = 70
  social-links = [
    { name = "Twitter", url = "https://twitter.com/mhmrth1" },
    { name = "GitHub", url = "https://github.com/Krak9n" }
  ]
  integrity = ""
  buildDrafts = true



baseURL = "https://vilgefortz.art/"
theme = "terminal"
relativeURLs = true
canonifyURLs = true


